name: Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest .
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest

      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: Projekt_TC
          dns-name-label: kalendarz-app-tc-${{ github.run_id }} 
          image: ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: kalendarz-app
          location: norwayeast
          ports: 80
          environment-variables: |
            MONGO_URI=${{ secrets.MONGO_URI_SECRET }}
            PORT=80