name: Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry (Docker)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest .
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:latest

      - name: Log in to Azure CLI via Registry Credentials
        run: |
          az login --service-principal -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} --tenant 50c76291-0c80-4444-a2fb-4f8ab168c311

      - name: Deploy to Azure Container Instances
        run: |
          az container create --resource-group Projekt_TC --file aci.yml